language: python

python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - pip install --user coverage
  - pip install --user codecov

script:
  - coverage run test/tests.py

after_success:
  - codecov
  
notifications:
  email: false
